galaxy_info:
  author: Bruce Becker
  description: Ansible Container playbooks for the FutureGateway Stack.
  company: C.S.I.R. Meraka Institute

  license: Apache-2.0

  min_ansible_container_version: 0.3.0-pre

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If travis integration is cofigured, only notification for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  tags: []
    # List tags for your app here, one per line. A tag is a keyword that describes and categorizes the app.
    # Users will find your app by searching for tags. Be sure to remove the '[]' above.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters. Maximum 20 tags.
